# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes-deployment
  namespace: remme-test
spec:
  selector:
    matchLabels:
      app: remme-node
  template:
    spec:
      metadata:
        labels:
          app: remme-node
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: validator-keys
        emptyDir: {}
      - name: genesis-data
        emptyDir: {}
      # Pull node settings
      initContainers:
      - name: init
        image: remme/remme-core:latest
        volumeMounts:
        - name: validator-keys
          mountPath: /etc/sawtooth/keys
        - name: genesis-data
          mountPath: /genesis/batch
        command:
        - sh
        args:
        - /project/scripts/genesis.sh
      # Run the node
      containers:
      - name: validator
        image: remme/sawtooth:latest
        volumeMounts:
        - name: validator-keys
          mountPath: /etc/sawtooth/keys
        - name: genesis-data
          mountPath: /genesis/batch
        ports:
        - name: external-nodes
          containerPort: 8800
          hostPort: 8800
        - name: component
          containerPort: 4004
        - name: consensus
          containerPort: 5005
        command:
        - sh
        args:
        - /scripts/validator.sh
      - name: consensus
        image: remme/remme-consensus:latest
        volumeMounts:
        - name: validator-keys
          mountPath: /etc/sawtooth/keys
        command:
        - cargo
        args:
        - run
        - --
        - --connect
        - tcp://127.0.0.1:5005
      - name: sawtooth-rest-api
        image: remme/sawtooth:latest
        ports:
        - name: http
          containerPort: 8008
        command:
        - sawtooth-rest-api
        args:
        - --connect
        - tcp://127.0.0.1:4004
        - --bind
        - 0.0.0.0:8008
      - name: block-info-tp
        image: remme/sawtooth:latest
        command:
        - block-info-tp
        args:
        - --connect
        - tcp://127.0.0.1:4004
      - name: settings-tp
        image: remme/sawtooth:latest
        command:
        - settings-tp
        args:
        - --connect
        - tcp://127.0.0.1:4004
      - name: remme-tp
        image: remme/remme-core:latest
        command:
        - python3
        args:
        - -m
        - remme.tp
      - name: remme-rpc-api
        image: remme/remme-core:latest
        command:
        - python3
        args:
        - -m
        - remme.rpc_api
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
